name: HardcorePlus
version: 1.4
main: me.minecraft.plugin.hardcoreplus.HardcorePlus
api-version: 1.20
authors: [ JustErikSK ]
description: Minecraft plugin for hardcore servers to make it more challenging but also more fun.
