name: HardcorePlus
version: 1.4
main: me.minecraft.plugin.hardcoreplus.HardcorePlus
api-version: 1.20
authors: [ JustErikSK ]
description: Do you like more challenging gameplay? Or even hardcore gameplay where most stuff is changed and it's really hard to progress? Well this plugin is made just for your server, so give it a try!
