name: HardcorePlus
version: 1.3.1d
main: me.minecraft.plugin.hardcoreplus.HardcorePlus
api-version: 1.19
authors: [ JustErikSK ]
description: Minecraft plugin for hardcore servers to make it more challenging but also more fun.
